DROP DATABASE IF EXISTS FORHEALTH;
CREATE DATABASE FORHEALTH;
USE FORHEALTH;
CREATE TABLE TIPO_USUARIO (
    id INT NOT NULL AUTO_INCREMENT,
    descricao VARCHAR(255) NOT NULL,
    CONSTRAINT pk PRIMARY KEY(id)
);
INSERT INTO TIPO_USUARIO (id, descricao) VALUES (1, 'ADMINISTRADOR');
INSERT INTO TIPO_USUARIO (id, descricao) VALUES (2, 'MÉDICO');
INSERT INTO TIPO_USUARIO (id, descricao) VALUES (3, 'PACIENTE');
CREATE TABLE USUARIO (
    id INT NOT NULL AUTO_INCREMENT,
    cpf VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    tipo_usuario INT NOT NULL,
    CONSTRAINT unique_cpf UNIQUE(cpf),
    CONSTRAINT pk_usr PRIMARY KEY(id),
    CONSTRAINT fk_usr_tipo FOREIGN KEY(tipo_usuario) REFERENCES TIPO_USUARIO(id)
);
INSERT INTO USUARIO (id, cpf, senha, ativo, tipo_usuario) VALUES (1, '478.371.780-09', '$2y$10$H.9myHAcYtDxY17FdcSNN.DrPJf.7x/6lqnRXAWRqIkvV4ppU72/6', 1, 1);
CREATE TABLE PACIENTE (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    uf VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    numero_casa VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    usuario INT,
    CONSTRAINT unique_paciente_usuario UNIQUE(usuario),
    CONSTRAINT pk_pac PRIMARY KEY(id),
    CONSTRAINT fk_pac_usr FOREIGN KEY(usuario) REFERENCES USUARIO(id)
);
CREATE TABLE MEDICO (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    crm VARCHAR(255) NOT NULL,
    especialidade VARCHAR(255) NOT NULL,
    usuario INT,
    CONSTRAINT unique_crm UNIQUE(crm),
    CONSTRAINT unique_medico_usuario UNIQUE(usuario),
    CONSTRAINT med_pk PRIMARY KEY(id),
    CONSTRAINT fk_med_usr FOREIGN KEY(usuario) REFERENCES USUARIO(id)
);
CREATE TABLE ATENDIMENTO_SOLICITACAO (
	id INT NOT NULL AUTO_INCREMENT,
    paciente INT NOT NULL,
	medico INT NOT NULL,
    aceito BOOLEAN DEFAULT NULL,
    data DATETIME NOT NULL,
    CONSTRAINT pk_ats PRIMARY KEY(id),
    CONSTRAINT fk_ats_pac FOREIGN KEY(paciente) REFERENCES PACIENTE(id),
    CONSTRAINT fk_ats_med FOREIGN KEY(medico) REFERENCES MEDICO(id)
);
CREATE TABLE EXAME (
	id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    resultado VARCHAR(800) NOT NULL,
    paciente INT NOT NULL,
    medico INT NOT NULL,
    laudo VARCHAR(800),
    data DATETIME NOT NULL,
    CONSTRAINT pk_exa PRIMARY KEY(id),    
    CONSTRAINT fk_exa_pac FOREIGN KEY(paciente) REFERENCES PACIENTE(id),    
    CONSTRAINT fk_exa_med FOREIGN KEY(medico) REFERENCES MEDICO(id)
);